/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamNewRouteImport } from './routes/team.new'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as TeamTeamIdPlayerIndexRouteImport } from './routes/team.$teamId.player.index'
import { Route as TeamTeamIdGameIndexRouteImport } from './routes/team.$teamId.game.index'
import { Route as TeamTeamIdPlayerNewRouteImport } from './routes/team.$teamId.player.new'
import { Route as TeamTeamIdGameNewRouteImport } from './routes/team.$teamId.game.new'
import { Route as TeamTeamIdGameGameIdIndexRouteImport } from './routes/team.$teamId.game.$gameId.index'
import { Route as TeamTeamIdGameGameIdStatsRouteImport } from './routes/team.$teamId.game.$gameId.stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamNewRoute = TeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdPlayerIndexRoute = TeamTeamIdPlayerIndexRouteImport.update({
  id: '/team/$teamId/player/',
  path: '/team/$teamId/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdGameIndexRoute = TeamTeamIdGameIndexRouteImport.update({
  id: '/team/$teamId/game/',
  path: '/team/$teamId/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdPlayerNewRoute = TeamTeamIdPlayerNewRouteImport.update({
  id: '/team/$teamId/player/new',
  path: '/team/$teamId/player/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdGameNewRoute = TeamTeamIdGameNewRouteImport.update({
  id: '/team/$teamId/game/new',
  path: '/team/$teamId/game/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdGameGameIdIndexRoute =
  TeamTeamIdGameGameIdIndexRouteImport.update({
    id: '/team/$teamId/game/$gameId/',
    path: '/team/$teamId/game/$gameId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamTeamIdGameGameIdStatsRoute =
  TeamTeamIdGameGameIdStatsRouteImport.update({
    id: '/team/$teamId/game/$gameId/stats',
    path: '/team/$teamId/game/$gameId/stats',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team/': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$teamId/game/new': typeof TeamTeamIdGameNewRoute
  '/team/$teamId/player/new': typeof TeamTeamIdPlayerNewRoute
  '/team/$teamId/game/': typeof TeamTeamIdGameIndexRoute
  '/team/$teamId/player/': typeof TeamTeamIdPlayerIndexRoute
  '/team/$teamId/game/$gameId/stats': typeof TeamTeamIdGameGameIdStatsRoute
  '/team/$teamId/game/$gameId/': typeof TeamTeamIdGameGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$teamId/game/new': typeof TeamTeamIdGameNewRoute
  '/team/$teamId/player/new': typeof TeamTeamIdPlayerNewRoute
  '/team/$teamId/game': typeof TeamTeamIdGameIndexRoute
  '/team/$teamId/player': typeof TeamTeamIdPlayerIndexRoute
  '/team/$teamId/game/$gameId/stats': typeof TeamTeamIdGameGameIdStatsRoute
  '/team/$teamId/game/$gameId': typeof TeamTeamIdGameGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team/': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$teamId/game/new': typeof TeamTeamIdGameNewRoute
  '/team/$teamId/player/new': typeof TeamTeamIdPlayerNewRoute
  '/team/$teamId/game/': typeof TeamTeamIdGameIndexRoute
  '/team/$teamId/player/': typeof TeamTeamIdPlayerIndexRoute
  '/team/$teamId/game/$gameId/stats': typeof TeamTeamIdGameGameIdStatsRoute
  '/team/$teamId/game/$gameId/': typeof TeamTeamIdGameGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/team/new'
    | '/team/'
    | '/api/trpc/$'
    | '/team/$teamId/game/new'
    | '/team/$teamId/player/new'
    | '/team/$teamId/game/'
    | '/team/$teamId/player/'
    | '/team/$teamId/game/$gameId/stats'
    | '/team/$teamId/game/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/team/new'
    | '/team'
    | '/api/trpc/$'
    | '/team/$teamId/game/new'
    | '/team/$teamId/player/new'
    | '/team/$teamId/game'
    | '/team/$teamId/player'
    | '/team/$teamId/game/$gameId/stats'
    | '/team/$teamId/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/team/new'
    | '/team/'
    | '/api/trpc/$'
    | '/team/$teamId/game/new'
    | '/team/$teamId/player/new'
    | '/team/$teamId/game/'
    | '/team/$teamId/player/'
    | '/team/$teamId/game/$gameId/stats'
    | '/team/$teamId/game/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamNewRoute: typeof TeamNewRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  TeamTeamIdGameNewRoute: typeof TeamTeamIdGameNewRoute
  TeamTeamIdPlayerNewRoute: typeof TeamTeamIdPlayerNewRoute
  TeamTeamIdGameIndexRoute: typeof TeamTeamIdGameIndexRoute
  TeamTeamIdPlayerIndexRoute: typeof TeamTeamIdPlayerIndexRoute
  TeamTeamIdGameGameIdStatsRoute: typeof TeamTeamIdGameGameIdStatsRoute
  TeamTeamIdGameGameIdIndexRoute: typeof TeamTeamIdGameGameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/new': {
      id: '/team/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof TeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/player/': {
      id: '/team/$teamId/player/'
      path: '/team/$teamId/player'
      fullPath: '/team/$teamId/player/'
      preLoaderRoute: typeof TeamTeamIdPlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/game/': {
      id: '/team/$teamId/game/'
      path: '/team/$teamId/game'
      fullPath: '/team/$teamId/game/'
      preLoaderRoute: typeof TeamTeamIdGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/player/new': {
      id: '/team/$teamId/player/new'
      path: '/team/$teamId/player/new'
      fullPath: '/team/$teamId/player/new'
      preLoaderRoute: typeof TeamTeamIdPlayerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/game/new': {
      id: '/team/$teamId/game/new'
      path: '/team/$teamId/game/new'
      fullPath: '/team/$teamId/game/new'
      preLoaderRoute: typeof TeamTeamIdGameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/game/$gameId/': {
      id: '/team/$teamId/game/$gameId/'
      path: '/team/$teamId/game/$gameId'
      fullPath: '/team/$teamId/game/$gameId/'
      preLoaderRoute: typeof TeamTeamIdGameGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/game/$gameId/stats': {
      id: '/team/$teamId/game/$gameId/stats'
      path: '/team/$teamId/game/$gameId/stats'
      fullPath: '/team/$teamId/game/$gameId/stats'
      preLoaderRoute: typeof TeamTeamIdGameGameIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamNewRoute: TeamNewRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  TeamTeamIdGameNewRoute: TeamTeamIdGameNewRoute,
  TeamTeamIdPlayerNewRoute: TeamTeamIdPlayerNewRoute,
  TeamTeamIdGameIndexRoute: TeamTeamIdGameIndexRoute,
  TeamTeamIdPlayerIndexRoute: TeamTeamIdPlayerIndexRoute,
  TeamTeamIdGameGameIdStatsRoute: TeamTeamIdGameGameIdStatsRoute,
  TeamTeamIdGameGameIdIndexRoute: TeamTeamIdGameGameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
