/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as TeamNewRouteImport } from './routes/team/new'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as TeamIdPlayerIndexRouteImport } from './routes/team/$id/player/index'
import { Route as TeamIdGameIndexRouteImport } from './routes/team/$id/game/index'
import { Route as TeamIdPlayerNewRouteImport } from './routes/team/$id/player/new'
import { Route as TeamIdGameNewRouteImport } from './routes/team/$id/game/new'
import { Route as TeamIdGameGameIdIndexRouteImport } from './routes/team/$id/game/$gameId/index'
import { Route as TeamIdGameGameIdStatsRouteImport } from './routes/team/$id/game/$gameId/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamNewRoute = TeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdPlayerIndexRoute = TeamIdPlayerIndexRouteImport.update({
  id: '/team/$id/player/',
  path: '/team/$id/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdGameIndexRoute = TeamIdGameIndexRouteImport.update({
  id: '/team/$id/game/',
  path: '/team/$id/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdPlayerNewRoute = TeamIdPlayerNewRouteImport.update({
  id: '/team/$id/player/new',
  path: '/team/$id/player/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdGameNewRoute = TeamIdGameNewRouteImport.update({
  id: '/team/$id/game/new',
  path: '/team/$id/game/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdGameGameIdIndexRoute = TeamIdGameGameIdIndexRouteImport.update({
  id: '/team/$id/game/$gameId/',
  path: '/team/$id/game/$gameId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdGameGameIdStatsRoute = TeamIdGameGameIdStatsRouteImport.update({
  id: '/team/$id/game/$gameId/stats',
  path: '/team/$id/game/$gameId/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team/': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$id/game/new': typeof TeamIdGameNewRoute
  '/team/$id/player/new': typeof TeamIdPlayerNewRoute
  '/team/$id/game/': typeof TeamIdGameIndexRoute
  '/team/$id/player/': typeof TeamIdPlayerIndexRoute
  '/team/$id/game/$gameId/stats': typeof TeamIdGameGameIdStatsRoute
  '/team/$id/game/$gameId/': typeof TeamIdGameGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$id/game/new': typeof TeamIdGameNewRoute
  '/team/$id/player/new': typeof TeamIdPlayerNewRoute
  '/team/$id/game': typeof TeamIdGameIndexRoute
  '/team/$id/player': typeof TeamIdPlayerIndexRoute
  '/team/$id/game/$gameId/stats': typeof TeamIdGameGameIdStatsRoute
  '/team/$id/game/$gameId': typeof TeamIdGameGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team/': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$id/game/new': typeof TeamIdGameNewRoute
  '/team/$id/player/new': typeof TeamIdPlayerNewRoute
  '/team/$id/game/': typeof TeamIdGameIndexRoute
  '/team/$id/player/': typeof TeamIdPlayerIndexRoute
  '/team/$id/game/$gameId/stats': typeof TeamIdGameGameIdStatsRoute
  '/team/$id/game/$gameId/': typeof TeamIdGameGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/team/new'
    | '/team/'
    | '/api/trpc/$'
    | '/team/$id/game/new'
    | '/team/$id/player/new'
    | '/team/$id/game/'
    | '/team/$id/player/'
    | '/team/$id/game/$gameId/stats'
    | '/team/$id/game/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/team/new'
    | '/team'
    | '/api/trpc/$'
    | '/team/$id/game/new'
    | '/team/$id/player/new'
    | '/team/$id/game'
    | '/team/$id/player'
    | '/team/$id/game/$gameId/stats'
    | '/team/$id/game/$gameId'
  id:
    | '__root__'
    | '/'
    | '/team/new'
    | '/team/'
    | '/api/trpc/$'
    | '/team/$id/game/new'
    | '/team/$id/player/new'
    | '/team/$id/game/'
    | '/team/$id/player/'
    | '/team/$id/game/$gameId/stats'
    | '/team/$id/game/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamNewRoute: typeof TeamNewRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  TeamIdGameNewRoute: typeof TeamIdGameNewRoute
  TeamIdPlayerNewRoute: typeof TeamIdPlayerNewRoute
  TeamIdGameIndexRoute: typeof TeamIdGameIndexRoute
  TeamIdPlayerIndexRoute: typeof TeamIdPlayerIndexRoute
  TeamIdGameGameIdStatsRoute: typeof TeamIdGameGameIdStatsRoute
  TeamIdGameGameIdIndexRoute: typeof TeamIdGameGameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/new': {
      id: '/team/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof TeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/player/': {
      id: '/team/$id/player/'
      path: '/team/$id/player'
      fullPath: '/team/$id/player/'
      preLoaderRoute: typeof TeamIdPlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/game/': {
      id: '/team/$id/game/'
      path: '/team/$id/game'
      fullPath: '/team/$id/game/'
      preLoaderRoute: typeof TeamIdGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/player/new': {
      id: '/team/$id/player/new'
      path: '/team/$id/player/new'
      fullPath: '/team/$id/player/new'
      preLoaderRoute: typeof TeamIdPlayerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/game/new': {
      id: '/team/$id/game/new'
      path: '/team/$id/game/new'
      fullPath: '/team/$id/game/new'
      preLoaderRoute: typeof TeamIdGameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/game/$gameId/': {
      id: '/team/$id/game/$gameId/'
      path: '/team/$id/game/$gameId'
      fullPath: '/team/$id/game/$gameId/'
      preLoaderRoute: typeof TeamIdGameGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/game/$gameId/stats': {
      id: '/team/$id/game/$gameId/stats'
      path: '/team/$id/game/$gameId/stats'
      fullPath: '/team/$id/game/$gameId/stats'
      preLoaderRoute: typeof TeamIdGameGameIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamNewRoute: TeamNewRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  TeamIdGameNewRoute: TeamIdGameNewRoute,
  TeamIdPlayerNewRoute: TeamIdPlayerNewRoute,
  TeamIdGameIndexRoute: TeamIdGameIndexRoute,
  TeamIdPlayerIndexRoute: TeamIdPlayerIndexRoute,
  TeamIdGameGameIdStatsRoute: TeamIdGameGameIdStatsRoute,
  TeamIdGameGameIdIndexRoute: TeamIdGameGameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
