/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamNewRouteImport } from './routes/team.new'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as TeamTeamIdGameIndexRouteImport } from './routes/team.$teamId.game.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamNewRoute = TeamNewRouteImport.update({
  id: '/team/new',
  path: '/team/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdGameIndexRoute = TeamTeamIdGameIndexRouteImport.update({
  id: '/team/$teamId/game/',
  path: '/team/$teamId/game/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team/': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$teamId/game/': typeof TeamTeamIdGameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$teamId/game': typeof TeamTeamIdGameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/team/new': typeof TeamNewRoute
  '/team/': typeof TeamIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/team/$teamId/game/': typeof TeamTeamIdGameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/team/new'
    | '/team/'
    | '/api/trpc/$'
    | '/team/$teamId/game/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/team/new' | '/team' | '/api/trpc/$' | '/team/$teamId/game'
  id:
    | '__root__'
    | '/'
    | '/team/new'
    | '/team/'
    | '/api/trpc/$'
    | '/team/$teamId/game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamNewRoute: typeof TeamNewRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  TeamTeamIdGameIndexRoute: typeof TeamTeamIdGameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/new': {
      id: '/team/new'
      path: '/team/new'
      fullPath: '/team/new'
      preLoaderRoute: typeof TeamNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId/game/': {
      id: '/team/$teamId/game/'
      path: '/team/$teamId/game'
      fullPath: '/team/$teamId/game/'
      preLoaderRoute: typeof TeamTeamIdGameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamNewRoute: TeamNewRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  TeamTeamIdGameIndexRoute: TeamTeamIdGameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
